import { pluralize } from "./helper-functions";

const adjectives = [
    'Fresh',
    'Civil',
    'Naked',
    'Glowing',
    'Rusty',
    'Occasional',
    'Honest',
    'Ernest',
    'Timely',
    'Shiny',
    'Eager',
    'Golden',
    'Envious',
    'Happy',
    'Friendly',
    'Royal',
    'Rabid',
    'Jolly',
    'Hazy',
    'Fallen',
    'Lost',
    'Wandering',
    'Known',
    'Broken',
    'Promised',
    'Proper',
    'Wishful',
    'Original',
    'Missing',
    'Stolen',
    'Smooth',
    'Pickled',
    'Ripe',
    'Hot',
    'Brass',
    'Living',
    'Extra',
    'Fancy',
    'Cheap',
    'Cherry',
    'Velvet',
    'Brave',
    'Cursed',
    'Mighty',
    'Reliable',
    'Obvious',
    'Neon',
    'Wicked',
    'Crimson',
    'Radiant',
    'Secret',
    'Cosmic',
    'Electric',
    'Paper',
    'Sly',
    'Sour',
    'Lucky',
    'Jealous',
    'Soaring',
    'Shimmering',
    'Midnight',
    'Nightly',
    'Solar',
    'Lunar',
    'Gracious',
    'Thriving',
    'Neighborly',
    'Rainbow',
    'Abundant',
    'Wealthy',
    'Deviant',
    'Leafy',
    'Available',
    'Loose',
    'Candy',
    'Peach',
    'Lemon',
    'Rising',
    'Morning',
    'Evening',
    'Virgin',
    'Decorative',
    'Swinging',
    'Uptown',
    'Downtown',
    'Lazy',
    'Scarlet',
    'Rainy',
    'Greatest',
    'Flying',
    'Frequent',
    'Earnest',
    'Urgent',
    'Top',
    'Bittersweet',
];

const nouns = [
    'Season',
    'Wizard',
    'Gnome',
    'Clover',
    'Chariot',
    'Zebra',
    'Wombat',
    'Possum',
    'Teacup',
    'Cupholder',
    'Coaster',
    'Turnip',
    'Lampshade',
    'Cheese',
    'Rat',
    'Banana',
    'Cabbage',
    'Monkey',
    'Tomato',
    'Ball',
    'Day',
    'Night',
    'Chance',
    'Pal',
    'Friend',
    'Neighbor',
    'Goose',
    'Hamster',
    'Pigeon',
    'Lightning',
    'Tiger',
    'Lizard',
    'Reptile',
    'Jet',
    'Pickle',
    'Dream',
    'Horse',
    'Lemur',
    'Rodent',
    'Pork Chop',
    'String Bean',
    'Bumblebee',
    'Sparrow',
    'Crow',
    'Raven',
    'Pelican',
    'Duckling',
    'Puppy',
    'Woodchuck',
    'Gopher',
    'Pea',
    'Peanut',
    'Siren',
    'Spotlight',
    'Dreamer',
    'Moonbeam',
    'Rocket',
    'Carousel',
    'Gondola',
    'Feather',
    'Unicorn',
    'Lantern',
    'Garden',
    'Horizon',
    'Pie',
    'Submarine',
    'Goat',
    'Berry',
    'Strawberry',
    'Grape',
    'Bunny',
    'Giraffe',
    'Woodchuck',
    'Penny',
    'Dragonfly',
    'Tree',
    'Appetizer',
    'Pot Pie',
    'Whisker',
    'Earthworm',
    'Penguin',
    'Tuesday'
];

const formats = [
    '{adj} {noun}',
    '{adj} {noun}',
    '{adj} {noun}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    'The {nouns}',
    'The {nouns}',
    '{noun} {noun}',
    '{noun} {noun}',
    'The {noun} {nouns}',
    'The {adj} {noun}',
    'The {adj} {noun}',
    'The {adj} {nouns}',
    'The {adj} {nouns}',
    'The {adj} {nouns}',
    'The {adj} {nouns}',
    'The {adj} {nouns}',
    'The {adj} {nouns}',
    'The {adj} {nouns}',
    'The {adj} {nouns}',
    '{nouns} and {nouns}',
    '{nouns} and {nouns}',
    '{nouns} and {nouns}',
    'The {adj}',
];

function rnd(arr: string[]): string {
    return arr[Math.floor(Math.random() * arr.length)];
}

export function nameGenerator(): string {
    let name = rnd(formats);
    while (name.includes('{')) {
        name = name
            .replace('{adj}', rnd(adjectives))
            .replace('{noun}', rnd(nouns))
            .replace('{nouns}', pluralize(rnd(nouns)))
    };
    return name;
}

export default nameGenerator
