const adjectives = [
    'Fresh',
    'Wet',
    'Civil',
    'Naked',
    'Glowing',
    'Rusty',
    'Occasional',
    'Frank',
    'Ernest',
    'Timely',
    'Shiny',
    'Avid',
    'Eager',
    'Golden',
    'Envious',
    'Happy',
    'Friendly',
    'Royal',
    'Rabid',
    'Jolly',
    'Misty',
    'Hazy',
    'Fallen',
    'Lost',
    'Wandering',
    'Known',
    'Broken',
    'Promised',
    'Missing',
    'Stolen',
    'Smooth',
    'Pickled',
    'Frozen',
    'Hot',
    'Brass',
    'Unspoken',
    'Living',
    'Extra',
    'Fancy',
    'Cheap',
    'Velvet',
    'Shy',
    'Brave',
    'Cursed',
    'Mighty',
    'Ancient',
    'Neon',
    'Wicked',
    'Crimson',
    'Radiant',
    'Secret',
    'Cosmic',
    'Electric',
    'Sly',
    'Sour',
    'Lucky',
    'Jealous',
    'Soaring',
    'Shimmering',
    'Midnight',
    'Solar',
    'Lunar',
    'Frosty',
    'Gracious',
    'Thriving',
    'Neighborly',
    'Rainbow',
    'Abundant'
];

const nouns = [
    'Wizard',
    'Floppy Disk',
    'Cupholder',
    'Turnip',
    'Lampshade',
    'Cheese',
    'Rat',
    'Banana',
    'Cabbage',
    'Monkey',
    'Stage',
    'Ball',
    'Day',
    'Night',
    'Chance',
    'Pal',
    'Friend',
    'Neighbor',
    'Machine',
    'Knuckle',
    'Hamster',
    'Pigeon',
    'Lightning',
    'Coward',
    'Paper Plane',
    'Lizard',
    'Reptile',
    'Jet',
    'Pickle',
    'Dream',
    'Horse',
    'Lemur',
    'Rodent',
    'Pork Chop',
    'String Bean',
    'Pea',
    'Paperback',
    'Siren',
    'Spotlight',
    'Dreamer',
    'Moonbeam',
    'Rocket',
    'Candle',
    'Carousel',
    'Gondola',
    'Feather',
    'Anchor',
    'Lantern',
    'Castle',
    'Garden',
    'Serpent',
    'Horizon',
    'Meatball',
    'Racecar',
    'Pie',
    'Submarine',
    'Explorer',
    'Berry'
];

const actions = [
    'Driving',
    'Playing',
    'Daring',
    'Catching',
    'Chasing',
    'Paying',
    'Baking',
    'Smoking',
    'Stealing',
    'Hazing',
    'Waking',
    'Riding',
    'Awakening',
    'Finding',
    'Drifting',
    'Floating',
    'Breaking',
    'Dreaming',
    'Summoning',
    'Spinning',
    'Climbing',
    'Wandering',
    'Charging',
    'Gliding'
];

const formats = [
    '{adj} {noun}',
    '{adj} {noun}',
    '{adj} {noun}',
    '{adj} {noun}',
    '{adj} {noun}s',
    '{adj} {noun}s',
    '{adj} {noun}s',
    '{adj} {noun}s',
    '{adj} {noun}s',
    '{adj} {noun}s',
    '{adj} {noun}s',
    '{adj} {noun}s',
    '{adj} {noun}s',
    '{adj} {noun}s',
    'The {noun}s',
    'The {noun}s',
    '{noun} {noun}',
    'The {noun} {noun}s',
    'The {adj} {noun}',
    'The {adj} {noun}',
    'The {adj} {noun}s',
    'The {adj} {noun}s',
    'The {adj} {noun}s',
    'The {adj} {noun}s',
    'The {adj} {noun}s',
    'The {adj} {noun}s',
    'The {adj} {noun}s',
    'The {adj} {noun}s',
    '{noun} and the {noun}s',
    '{noun}s and {noun}s',
    '{noun}s and {noun}s',
    '{noun}s and {noun}s',
    '{noun}s and {adj} {noun}s',
    '{act} the {noun}',
    '{act} {noun}s',
    '{act} {noun}s',
    '{act} the {noun}s',
    '{adj} {adj} {noun}s',
    'The {adj}',
    '{act} With {noun}s',
    'The {noun} and the {noun}'
];

function rnd(max: number): number {
    return Math.floor(Math.random() * max)
}

export function nameGenerator(): string {
    return formats[rnd(formats.length)]
        .replace('{adj}', adjectives[rnd(adjectives.length)])
        .replace('{adj}', adjectives[rnd(adjectives.length)])
        .replace('{noun}', nouns[rnd(nouns.length)])
        .replace('{noun}', nouns[rnd(nouns.length)])
        .replace('{act}', actions[rnd(actions.length)])
        .replaceAll('rys', 'ries');
}

export default nameGenerator
