import { pluralize } from "./helper-functions";

const adjectives = [
    'Fresh',
    'Wet',
    'Civil',
    'Naked',
    'Glowing',
    'Rusty',
    'Occasional',
    'Frank',
    'Ernest',
    'Timely',
    'Shiny',
    'Avid',
    'Eager',
    'Golden',
    'Envious',
    'Happy',
    'Friendly',
    'Royal',
    'Rabid',
    'Jolly',
    'Misty',
    'Hazy',
    'Fallen',
    'Lost',
    'Wandering',
    'Known',
    'Broken',
    'Promised',
    'Missing',
    'Stolen',
    'Smooth',
    'Pickled',
    'Ripe',
    'Hot',
    'Brass',
    'Living',
    'Extra',
    'Fancy',
    'Cheap',
    'Velvet',
    'Shy',
    'Brave',
    'Cursed',
    'Mighty',
    'Ancient',
    'Neon',
    'Wicked',
    'Crimson',
    'Radiant',
    'Secret',
    'Cosmic',
    'Electric',
    'Paper',
    'Sly',
    'Sour',
    'Lucky',
    'Jealous',
    'Soaring',
    'Shimmering',
    'Midnight',
    'Solar',
    'Lunar',
    'Frosty',
    'Gracious',
    'Thriving',
    'Neighborly',
    'Rainbow',
    'Abundant',
    'Wealthy',
    'Deviant',
    'Leafy',
    'Available',
    'Loose',
    'Candy',
    'Peach'
];

const nouns = [
    'Wizard',
    'Gnome',
    'Cupholder',
    'Coaster',
    'Turnip',
    'Lampshade',
    'Cheese',
    'Rat',
    'Banana',
    'Cabbage',
    'Monkey',
    'Tomato',
    'Ball',
    'Day',
    'Night',
    'Chance',
    'Pal',
    'Friend',
    'Neighbor',
    'Machine',
    'Knuckle',
    'Hamster',
    'Pigeon',
    'Lightning',
    'Coward',
    'Tiger',
    'Lizard',
    'Reptile',
    'Jet',
    'Pickle',
    'Dream',
    'Horse',
    'Lemur',
    'Rodent',
    'Pork Chop',
    'String Bean',
    'Pea',
    'Peanut',
    'Siren',
    'Spotlight',
    'Dreamer',
    'Moonbeam',
    'Rocket',
    'Candle',
    'Carousel',
    'Gondola',
    'Feather',
    'Unicorn',
    'Lantern',
    'Castle',
    'Garden',
    'Horizon',
    'Pie',
    'Submarine',
    'Explorer',
    'Berry',
    'Strawberry',
    'Grape',
    'Bunny',
    'Giraffe',
    'Woodchuck',
    'Penny',
    'Swinging',
    'Dragonfly',
    'Tree',
    'Appetizer'
];

const formats = [
    '{adj} {noun}',
    '{adj} {noun}',
    '{adj} {noun}',
    '{adj} {noun}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    '{adj} {nouns}',
    'The {nouns}',
    'The {nouns}',
    '{noun} {noun}',
    'The {noun} {nouns}',
    'The {adj} {noun}',
    'The {adj} {noun}',
    'The {adj} {nouns}',
    'The {adj} {nouns}',
    'The {adj} {nouns}',
    'The {adj} {nouns}',
    'The {adj} {nouns}',
    'The {adj} {nouns}',
    'The {adj} {nouns}',
    'The {adj} {nouns}',
    '{noun} and the {nouns}',
    '{nouns} and {nouns}',
    '{nouns} and {nouns}',
    '{nouns} and {nouns}',
    'The {adj}',
    'The {noun} and the {noun}'
];

function rnd(arr: string[]): string {
    return arr[Math.floor(Math.random() * arr.length)];
}

export function nameGenerator(): string {
    let name = rnd(formats);
    while (name.includes('{')) {
        name = name
            .replace('{adj}', rnd(adjectives))
            .replace('{noun}', rnd(nouns))
            .replace('{nouns}', pluralize(rnd(nouns)))
    };
    return name;
}

export default nameGenerator
